import LocalizedStrings from 'react-native-localization';

export default strings = new LocalizedStrings({
    en:{
      Next:"Next",
      Prev:"prev",
      transporter:"Transporter",
      client:"Client",
      yourNumber:"Enter Your Phone Number",
      yourPassword:"Enter Your Password",
      yourName:"Enter Your Name",
      confirmPassword:"Confirm Your Password",
      forgetPassword:"Forget Password?",
      signIn:"Sign In",
      noAccount:"Don't have an account?",
      createAccount:"Create new account",
      point:"Point",
      signUp:"Sign Up",
      moreInfo:"More info",
      Description:"Description",
      category:"Category",
      Weight:"Weight",
      ArrivalTime:"Arrival Time",
      ArrivalDate:"Arrival Date",
      EndPoint:"End Point",
      firstPoint:"first Point",
      Details:"Details",
      Request:"Request",
      postPage:"Post Page",
      from:"From",
      to:"To",
      title:"Title",
      date:"Date",
      selectDate:"select Date",
      confirm:"Confirm",
      cancel:"Cancel",
      time:"Time",
      writeDescription:"Write Description Here",
      post:"Post",
      newPassword:"New Password",
      send:"Send",
      activation:"Activation",
      activationCode:"Activation code",
      enterCode:"Please Enter The Code sent to phone",
      ActivationCodeDuration:"Activation Code Will Reach During 30 Secounds",
      resendActivationCode:"Resend Activation Code?",
      confermation:"Confirmation",
      yourEmail:"Enter Your E-mail",
      changePassword:"Change Password",
      save:"Save",
      privacy:"Privacy",
      welcome:"Welcome to",
      forgetPass:"Forget password",
      note:"Note : This Phone Will get Activation Code",
      contactUs:"Contact Us",
      email:"E-mail",
      phone:"Phone",
      WebSite:"WebSite",
      message:"Message",
      writeMessage:"Write Your Message",
      home:"Home",
      Newpost:"New post",
      AboutUs:"About Us",
      profilesettings:"profile settings",
      policy:"Privacy & policy",
      WriteActivationCode:"Please Write An Activation Code",
      insertVALIDactivationcode:"please insert VALID activation code",
      activationcodesendedsuccessfuly:"activation code sended successfuly",
      dataSaved:"data saved",
      pleaseTryAgain:"please try again",
      WriteYourPhone:"Please Write Your Phone",
      CompleteTheForm:'Please Complete The Form',
      PasswordNotMatched:"Password not matched",
      insertCorrectPhoneAndPassword:"please insert correct phone and password",
      WriteCorrectPhoneNumber:"Please Write Correct Phone Number",
      DataUpdatedSuccessfuly:"Data Updated Successfuly",
      WriteYourPhoneAndPassword:"Please Write Your Phone and Password",
      FullAllData:"Please Full All Data",
      DataInsertedSuccessfuly:"Data Inserted Successfuly"
    },
    ar: {
      Next:"التالى",
      Prev:"السابق",
      transporter:"مسافر",
      client:"عميل",
      yourNumber:"ادخل رقم هاتفك",
      yourPassword:"ادخل كلمه السر",
      forgetPassword:"نسيت كلمة السر؟",
      yourName:"ادخل اسمك",
      confirmPassword:"اكد كلمه السر",
      signIn:"دخول",
      noAccount:"لا تملك حساب؟",
      createAccount:"انشاء حساب جديد",
      point:"نقطة",
      signUp:"انشاء",
      moreInfo:"المزيد من المعلومات",
      Description:"الوصف",
      category:"الفئه",
      Weight:"الوزن",
      ArrivalTime:"وقت الوصول",
      ArrivalDate:"تاريخ الوصول",
      EndPoint:"نقطة النهايه",
      firstPoint:"نقطة البدايه",
      Details:"التفاصيل",
      Request:"طلب",
      postPage:"انشاء منشور جديد",
      from:"من",
      to:"الى",
      title:"الاسم",
      date:"التاريخ",
      selectDate:"اختر تاريخ",
      confirm:"تأكيد",
      cancel:"الغاء",
      time:"الوقت",
      writeDescription:"اكتب الوصف هنا",
      post:"نشر",
      newPassword:"كلمة مرور جديدة",
      send:"ارسال",
      activation:"تفعيل",
      activationCode:"رمز التفعيل",
      enterCode:"ادخل الرمز المرسل الى الهاتف",
      ActivationCodeDuration:"رمز التفعيل سيصل خلال 30 ثانيه",
      resendActivationCode:"اعادة ارسال رمز التفعيل؟",
      confermation:"تأكيد",
      yourEmail:"ادخل البريد الالكترونى",
      changePassword:"تغيير كلمة المرور",
      save:"حفظ",
      privacy:"الخصوصيه",
      welcome:"اهلا بك",
      forgetPass:"نسيت رقم المرور",
      note:"ملاحظه: سيصل رمز التفعيل الى هذا الهاتف",
      contactUs:"تواصل معنا",
      email:"البريد الالكترونى",
      phone:"الهاتف",
      WebSite:"موقع الكتروني",
      message:"رساله",
      writeMessage:"اكتب رسالتك",
      home:"الصفحه الرئيسيه",
      Newpost:"منشور جديد",
      AboutUs:"من نحن؟",
      profilesettings:"اعدادات",
      policy:"الشروط والاحكام",
      WriteActivationCode:"من فضلك ادخل رمز التفعيل",
      insertVALIDactivationcode:"من فضلك ادخل رمز تفعيل صحيح",
      activationcodesendedsuccessfuly:"تم ارسال رمز التفعيل بنجاح",
      dataSaved:"تم تخزين البيانات",
      pleaseTryAgain:"من فضلك حاول مجددا",
      WriteYourPhone:"من فضلك ادخل رقم هاتفك",
      CompleteTheForm:'من فضلك اكمل باقى البيانات',
      PasswordNotMatched:"كلمات المرور غير متطابقه",
      insertCorrectPhoneAndPassword:"من فضلك اخل رقم هاتف و كلمه مرور بشكل صحيح",
      WriteCorrectPhoneNumber:"من فضلك ادخل رقم هاتف صحيح",
      DataUpdatedSuccessfuly:"تم تحديث البيانات بنجاح",
      WriteYourPhoneAndPassword:"من فضلك ادخل رقم هاتفك وكلمة المرور الخاصه بك",
      FullAllData:"من فضلك ادخل جميع البيانات",
      DataInsertedSuccessfuly:"تم دخول البيانات بنجاح"
    }
   });